CREATE DATABASE IF NOT EXISTS leave_mgmt;
USE leave_mgmt;

CREATE TABLE IF NOT EXISTS Employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  department VARCHAR(100) NOT NULL,
  joiningDate DATE NOT NULL,
  leaveBalance INT NOT NULL DEFAULT 20
);

CREATE TABLE IF NOT EXISTS HRs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Leaves (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employeeId INT NOT NULL,
  startDate DATE NOT NULL,
  endDate DATE NOT NULL,
  reason VARCHAR(255),
  status ENUM('Pending','Approved','Rejected') DEFAULT 'Pending',
  CONSTRAINT fk_emp FOREIGN KEY (employeeId) REFERENCES Employees(id) ON DELETE CASCADE
);